version: '3.8'

services:
  backend:
    image: n3k14/backend:latest
    container_name: mini_proj.backend
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    image: n3k14/frontend:latest
    container_name: mini_proj.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  database:
    image: postgres:latest
    container_name: mini_proj.database
    environment:
      POSTGRES_DB: mini_proj
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pg_data: