networks:
  app-network:

services:
  database:
    image: postgres:latest
    container_name: mini_proj.database
    environment:
      POSTGRES_DB: mini_proj
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mini_proj"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app-network

  backend:
    image: n3k14/backend:latest
    container_name: mini_proj.backend
    depends_on:
      database:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    image: n3k14/frontend:latest
    container_name: mini_proj.frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

volumes:
  pg_data: